# Generated by Django 4.2.1 on 2023-05-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_desc_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
    ]
